Fix process shutdown on Android
saltstack/pytest-shell-utilities pull request #51
Opened 2024-10-12 14:24 UTC by dead10ck

- **upgrade psutil to 6.0.0**

- **fix: handle process shutdown with limited permissions**

Certain platforms like Android do not have permission to list all child processes. In this instance, just continue

2024-10-14 16:40 UTC, dmurphy18 requested changes
You need to rebase against current, psutil is already updated to version 6.0.0. (done a few week sback)
Then retest your changes, always best to ensure rebased against latest before submitting a PR

2024-10-17 02:36 UTC, dead10ck commented
Done

2024-10-17 15:20 UTC, dmurphy18 approved these changes

2024-10-17 20:46 UTC, merged

2024-10-17 20:51 UTC, dmurphy18 commented
Merged the PR by hand into the main branch, due to to the docs/readthedocs.org:pytest-shell-utilities requirement is met on https://readthedocs.org/projects/pytest-shell-utilities/builds/, but the passed response appears to not have made it back to Github.

2024-10-17 20:51 UTC, dmurphy18 commented
@dead10ck Just released version 1.9.4 with your fix for pytest-shell-utilities

2024-10-17 20:52 UTC, dead10ck commented
Thank you!